//! babeld configuration generation.
//!
//! mjolnir-mesh manages babeld's config file from CRDT state. The daemon
//! regenerates the file when its subnet claim or active-peer set changes and
//! writes it atomically; on change the `mjolnir-babeld` procd service is
//! restarted to pick it up (babeld 1.13 exits on SIGHUP, so a clean restart, not
//! a signal-reload — mjolnir-mesh-m8t). See docs/network-coordination/
//! babel-routing.md §5.

use ipnet::Ipv4Net;
use std::io;
use std::path::Path;

/// Inputs to the config renderer. All fields are required.
#[derive(Debug, Clone)]
pub struct BabelConfigInputs<'a> {
    /// This router's claimed /24 (or larger). One per router. Optional only
    /// for the brief startup window before a claim has been published —
    /// during that window, no `redistribute ip` line is emitted.
    pub local_subnet: Option<Ipv4Net>,
    /// Per-peer TUN interface names currently up (from US-004's PeerInterface).
    pub peer_interfaces: &'a [&'a str],
    /// Shared-L2 backhaul interfaces babel speaks over directly (`type wireless` + RTT)
    /// (mjolnir-mesh-auu). On a multicast-capable segment babeld auto-discovers
    /// every other node's babel speaker — no per-peer tunnel needed. This is the
    /// LAN data plane that replaces the flaky per-peer iroh tunnels for same-site
    /// peers; `peer_interfaces` (tunnels) remain for off-LAN routing.
    pub l2_interfaces: &'a [&'a str],
    /// Default rxcost for tunneled neighbors. babeld defaults are 96 for
    /// non-multicast (tunnel) interfaces.
    pub tunnel_rxcost: u16,
    /// Internet gateway role (mjolnir-mesh-a8o): redistribute this node's WAN
    /// default route into the mesh so other nodes (and their clients) egress
    /// via it. babeld tracks the kernel — no uplink means no 0.0.0.0/0 in the
    /// FIB, so the announcement withdraws automatically on WAN loss, and
    /// multiple gateways compete on metric+path cost (nearest exit wins).
    pub gateway: bool,
}

impl<'a> BabelConfigInputs<'a> {
    /// Recommended defaults matching babel-routing.md §5.
    pub fn new(local_subnet: Option<Ipv4Net>, peer_interfaces: &'a [&'a str]) -> Self {
        Self {
            local_subnet,
            peer_interfaces,
            l2_interfaces: &[],
            tunnel_rxcost: 96,
            gateway: false,
        }
    }

    /// Add shared-L2 backhaul interfaces (rendered as `type wireless` with the RTT metric).
    pub fn l2_interfaces(mut self, l2_interfaces: &'a [&'a str]) -> Self {
        self.l2_interfaces = l2_interfaces;
        self
    }

    /// Mark this node as an internet gateway (mjolnir-mesh-a8o).
    pub fn gateway(mut self, gateway: bool) -> Self {
        self.gateway = gateway;
        self
    }
}

/// Render the full babeld.conf body. Pure — no I/O.
///
/// Output (golden, matches babel-routing.md §5):
/// ```text
/// # Generated by mjolnir-mesh — do not edit by hand
///
/// interface mj-peer-aabbccdd type tunnel
/// interface mj-peer-eeff0011 type tunnel
///
/// redistribute ip 10.42.1.0/24 allow
/// redistribute local deny
/// redistribute deny
///
/// in ip 10.255.0.0/16 deny
/// out ip 10.255.0.0/16 deny
///
/// default rxcost 96
/// ```
pub fn render_babeld_conf(inputs: &BabelConfigInputs<'_>) -> String {
    let mut out = String::new();
    out.push_str("# Generated by mjolnir-mesh — do not edit by hand\n\n");

    // Shared-L2 backhaul interfaces first: babeld multicast-discovers every
    // other node on the segment (mjolnir-mesh-auu). The segment is an 802.11s
    // radio, so `type wireless` + the RTT metric, not `type wired` (kf7 field
    // session 2026-07-01): flat wired cost pinned a -80 dBm MCS2 link
    // (20 Mbit/s) over a clean 2-hop relay (90/56 Mbit/s legs), and hello-loss
    // ETX alone barely moves the cost because multicast hellos ride robust
    // basic rates that don't reflect data-rate degradation. Queueing delay
    // under load IS visible to protocol packets, hence timestamps: rtt-min 10
    // (idle LAN ~2-7 ms → no penalty), and max-rtt-penalty 150 so a saturated
    // weak link (96+150=246) can lose to a clean 2-hop relay (2×96=192).
    for iface in inputs.l2_interfaces {
        out.push_str(&format!(
            "interface {} type wireless enable-timestamps true \
             rtt-min {} rtt-max {} max-rtt-penalty {} rtt-decay {}\n",
            iface, L2_RTT.rtt_min_ms, L2_RTT.rtt_max_ms, L2_RTT.max_rtt_penalty, L2_RTT.rtt_decay
        ));
    }
    for iface in inputs.peer_interfaces {
        out.push_str(&format!("interface {} type tunnel\n", iface));
    }
    if !inputs.l2_interfaces.is_empty() || !inputs.peer_interfaces.is_empty() {
        out.push('\n');
    }

    // No ge/le qualifiers on the allow (kf7): with `ge 24 le 24` babeld 1.13
    // silently exports NOTHING — proven on hardware via SIGUSR1 xroute dumps
    // (no /24 exported with the qualifiers, exported immediately without).
    if let Some(subnet) = inputs.local_subnet {
        out.push_str(&format!("redistribute ip {} allow\n", subnet));
    }
    // Gateway role (a8o): announce the kernel's default route into the mesh.
    // `le 0` matches ONLY 0.0.0.0/0; `metric 128` is the filter action (metric
    // implies allow in babeld), leaving headroom for babel's per-hop link costs
    // so nearest-exit selection works across multiple gateways. Validated live
    // on the fleet: hand-injected on the TR3000, m3000 learned `default via`
    // and reached 8.8.8.8 through the gateway's existing wan-zone masquerade.
    if inputs.gateway {
        out.push_str("redistribute ip 0.0.0.0/0 le 0 metric 128\n");
    }
    // Deny local interface addresses explicitly (nrr): a bare `redistribute
    // deny` does NOT cover babeld's implicit local-address export (same lesson
    // as the overlay render, buw.1) — without this every node exported junk
    // /32s fleet-wide (192.168.1.1 from all nodes, the gateway's WAN address,
    // ULAs). The claimed .1 stays reachable via the /24 allow above.
    out.push_str("redistribute local deny\n");
    // Catch-all: deny redistributing everything not explicitly allowed above.
    // babeld's `proto` filter takes a NUMERIC protocol, not a name, so the old
    // `redistribute proto static/kernel deny` lines made real babeld (1.13)
    // reject the whole config with a parse error (found on hardware, apo). A
    // bare `redistribute deny` is the idiomatic, valid way to redistribute only
    // our claimed /24.
    out.push_str("redistribute deny\n\n");

    out.push_str("in ip 10.255.0.0/16 deny\n");
    out.push_str("out ip 10.255.0.0/16 deny\n\n");

    out.push_str(&format!("default rxcost {}\n", inputs.tunnel_rxcost));
    out
}

/// babeld RTT-metric parameters for the single overlay TUN (mjolnir-mesh-buw.5).
///
/// The overlay is a QUIC tunnel whose measured latency is a good signal of path
/// quality (direct vs relayed, congested vs idle), so babeld's timestamp-based
/// RTT metric auto-deprioritises high-latency / relay paths instead of using a
/// fixed rxcost. Below `rtt_min_ms` no penalty is added (LAN/direct); between
/// `rtt_min_ms` and `rtt_max_ms` the penalty rises linearly up to
/// `max_rtt_penalty`; `rtt_decay` smooths the RTT estimate (1/256 units).
/// Validated end-to-end in mjolnir-mesh-buw.1 (RTT observed active: `rttcost`
/// tracks measured `rtt`).
#[derive(Debug, Clone, Copy)]
pub struct OverlayRtt {
    pub rtt_min_ms: u32,
    pub rtt_max_ms: u32,
    pub max_rtt_penalty: u16,
    pub rtt_decay: u16,
}

impl Default for OverlayRtt {
    fn default() -> Self {
        Self {
            rtt_min_ms: 10,
            rtt_max_ms: 200,
            max_rtt_penalty: 96,
            rtt_decay: 42,
        }
    }
}

/// RTT-metric parameters for the shared-L2 radio backhaul (see the comment in
/// [`render_babeld_conf`] for the field evidence behind these values). Tighter
/// `rtt_max_ms` and a larger penalty than the overlay defaults: LAN idle RTT is
/// ~2-7 ms, and the penalty must be able to push a saturated weak link past the
/// cost of a clean 2-hop relay.
const L2_RTT: OverlayRtt = OverlayRtt {
    rtt_min_ms: 10,
    rtt_max_ms: 120,
    max_rtt_penalty: 150,
    rtt_decay: 42,
};

/// Render babeld.conf for the buw single-overlay-TUN data plane: ONE static
/// `iface` (e.g. `mjolnir0`) carrying every peer, so the file never changes as
/// peers come and go. That static-ness is the whole point — the per-peer
/// interface churn is what wedged meshd via rapid procd restarts
/// (mjolnir-mesh-qz9); with one permanent interface there is nothing to churn.
///
/// Pure — no I/O. Differences from [`render_babeld_conf`]'s per-peer output:
///   - a single `type tunnel` interface with the RTT metric enabled
///     (`enable-timestamps` + `rtt-*`), not N per-peer lines;
///   - the overlay-link block `10.254.0.0/16` is denied in BOTH directions (in
///     addition to the legacy TUN-link `10.255.0.0/16`), and `redistribute local
///     deny` is explicit. Redistributing a node's own overlay address makes
///     babeld install an `unreachable <peer>/32` more specific than the on-link
///     route, which — if that address is used for transport — poisons the very
///     path the overlay rides on (root-caused in mjolnir-mesh-buw.1). Only the
///     claimed client `/24` is ever advertised.
pub fn render_overlay_babeld_conf(
    iface: &str,
    local_subnet: Option<Ipv4Net>,
    rtt: OverlayRtt,
    gateway: bool,
) -> String {
    let mut out = String::new();
    out.push_str("# Generated by mjolnir-mesh — do not edit by hand\n\n");

    // ONE static interface for ALL peers (kills per-peer config churn / qz9).
    out.push_str(&format!(
        "interface {iface} type tunnel enable-timestamps true \
         rtt-min {} rtt-max {} max-rtt-penalty {} rtt-decay {}\n\n",
        rtt.rtt_min_ms, rtt.rtt_max_ms, rtt.max_rtt_penalty, rtt.rtt_decay
    ));

    // No ge/le qualifiers (kf7): they silently defeat the match in babeld 1.13.
    if let Some(subnet) = local_subnet {
        out.push_str(&format!("redistribute ip {} allow\n", subnet));
    }
    // Gateway role (a8o) — same semantics as the LAN render: kernel default
    // route in, auto-withdrawn with the uplink, metric leaves room for RTT cost.
    if gateway {
        out.push_str("redistribute ip 0.0.0.0/0 le 0 metric 128\n");
    }
    // Advertise ONLY the claimed client /24: deny local interface addresses and
    // everything else not explicitly allowed above.
    out.push_str("redistribute local deny\n");
    out.push_str("redistribute deny\n\n");

    // Never route/redistribute the transport blocks — see the doc comment.
    out.push_str("in ip 10.254.0.0/16 deny\n");
    out.push_str("out ip 10.254.0.0/16 deny\n");
    out.push_str("in ip 10.255.0.0/16 deny\n");
    out.push_str("out ip 10.255.0.0/16 deny\n");
    out
}

/// Write `contents` atomically to `path` — tmp file + rename in the same directory.
/// Returns `Ok(true)` if the file was written (content differed or didn't exist),
/// `Ok(false)` if the on-disk content already matched and no write was performed.
pub fn write_atomic_if_changed(path: &Path, contents: &str) -> io::Result<bool> {
    if let Ok(existing) = std::fs::read_to_string(path)
        && existing == contents
    {
        return Ok(false);
    }
    let parent = path.parent().ok_or_else(|| {
        io::Error::new(io::ErrorKind::InvalidInput, "config path has no parent dir")
    })?;
    // Random-ish suffix; collisions tolerable since we're single-process.
    let pid = std::process::id();
    let tmp = parent.join(format!(
        ".{}-{}.tmp",
        path.file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("babeld.conf"),
        pid
    ));
    std::fs::write(&tmp, contents)?;
    std::fs::rename(&tmp, path)?;
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_overlay_matches_golden() {
        // Golden output validated end-to-end against real babeld in buw.1.
        let subnet: Ipv4Net = "10.42.1.0/24".parse().unwrap();
        let got =
            render_overlay_babeld_conf("mjolnir0", Some(subnet), OverlayRtt::default(), false);
        let expected = "\
# Generated by mjolnir-mesh — do not edit by hand

interface mjolnir0 type tunnel enable-timestamps true rtt-min 10 rtt-max 200 max-rtt-penalty 96 rtt-decay 42

redistribute ip 10.42.1.0/24 allow
redistribute local deny
redistribute deny

in ip 10.254.0.0/16 deny
out ip 10.254.0.0/16 deny
in ip 10.255.0.0/16 deny
out ip 10.255.0.0/16 deny
";
        assert_eq!(got, expected);
    }

    #[test]
    fn render_overlay_is_static_regardless_of_peers() {
        // The whole qz9 fix: exactly ONE interface line, and it never mentions a
        // per-peer mj-peer-* interface — so the file cannot churn as peers change.
        let subnet: Ipv4Net = "10.42.9.0/24".parse().unwrap();
        let got =
            render_overlay_babeld_conf("mjolnir0", Some(subnet), OverlayRtt::default(), false);
        assert_eq!(
            got.matches("\ninterface ").count() + got.starts_with("interface ") as usize,
            1
        );
        assert!(
            !got.contains("mj-peer-"),
            "must have no per-peer interfaces"
        );
        assert!(got.contains("interface mjolnir0 type tunnel"));
    }

    #[test]
    fn render_overlay_denies_transport_blocks_and_locals() {
        // Redistributing a node's own transport address poisons the path (buw.1).
        let got = render_overlay_babeld_conf("mjolnir0", None, OverlayRtt::default(), false);
        assert!(got.contains("redistribute local deny"));
        assert!(got.contains("in ip 10.254.0.0/16 deny"));
        assert!(got.contains("out ip 10.254.0.0/16 deny"));
        assert!(got.contains("in ip 10.255.0.0/16 deny"));
        // No client subnet claimed yet -> no redistribute-allow line.
        assert!(!got.contains("redistribute ip"));
    }

    #[test]
    fn render_overlay_custom_rtt_params() {
        let subnet: Ipv4Net = "10.42.1.0/24".parse().unwrap();
        let rtt = OverlayRtt {
            rtt_min_ms: 5,
            rtt_max_ms: 400,
            max_rtt_penalty: 150,
            rtt_decay: 30,
        };
        let got = render_overlay_babeld_conf("mjolnir0", Some(subnet), rtt, false);
        assert!(got.contains("rtt-min 5 rtt-max 400 max-rtt-penalty 150 rtt-decay 30"));
    }

    #[test]
    fn render_l2_backhaul_as_wireless_rtt_before_tunnels() {
        // mjolnir-mesh-auu: the shared-L2 backhaul renders ahead of any
        // per-peer tunnel interfaces; kf7: as `type wireless` with the RTT
        // metric so babel can see radio link quality.
        let subnet: Ipv4Net = "10.42.1.0/24".parse().unwrap();
        let l2 = ["veth-mesh"];
        let inputs = BabelConfigInputs::new(Some(subnet), &[]).l2_interfaces(&l2);
        let got = render_babeld_conf(&inputs);
        let expected = "\
# Generated by mjolnir-mesh — do not edit by hand

interface veth-mesh type wireless enable-timestamps true rtt-min 10 rtt-max 120 max-rtt-penalty 150 rtt-decay 42

redistribute ip 10.42.1.0/24 allow
redistribute local deny
redistribute deny

in ip 10.255.0.0/16 deny
out ip 10.255.0.0/16 deny

default rxcost 96
";
        assert_eq!(got, expected);
    }

    #[test]
    fn render_matches_golden_with_two_peers_and_subnet() {
        let subnet: Ipv4Net = "10.42.1.0/24".parse().unwrap();
        let peers = ["mj-peer-aabbccdd", "mj-peer-eeff0011"];
        let inputs = BabelConfigInputs::new(Some(subnet), &peers);
        let got = render_babeld_conf(&inputs);
        let expected = "\
# Generated by mjolnir-mesh — do not edit by hand

interface mj-peer-aabbccdd type tunnel
interface mj-peer-eeff0011 type tunnel

redistribute ip 10.42.1.0/24 allow
redistribute local deny
redistribute deny

in ip 10.255.0.0/16 deny
out ip 10.255.0.0/16 deny

default rxcost 96
";
        assert_eq!(got, expected);
    }

    #[test]
    fn render_omits_redistribute_when_no_local_subnet() {
        let peers = ["mj-peer-aabbccdd"];
        let inputs = BabelConfigInputs::new(None, &peers);
        let got = render_babeld_conf(&inputs);
        assert!(
            !got.contains("redistribute ip"),
            "should have no redistribute ip line"
        );
        assert!(got.contains("redistribute deny"));
    }

    #[test]
    fn render_with_no_peers_omits_interface_block() {
        let subnet: Ipv4Net = "10.42.1.0/24".parse().unwrap();
        let peers: &[&str] = &[];
        let inputs = BabelConfigInputs::new(Some(subnet), peers);
        let got = render_babeld_conf(&inputs);
        assert!(!got.contains("interface"), "should have no interface lines");
        // No double blank line where the block would have been — header blank + no extra
        let expected_start = "# Generated by mjolnir-mesh — do not edit by hand\n\nredistribute";
        assert!(got.starts_with(expected_start), "unexpected start:\n{got}");
    }

    #[test]
    fn render_with_custom_rxcost() {
        let peers: &[&str] = &[];
        let mut inputs = BabelConfigInputs::new(None, peers);
        inputs.tunnel_rxcost = 200;
        let got = render_babeld_conf(&inputs);
        assert!(got.ends_with("default rxcost 200\n"));
    }

    #[test]
    fn render_gateway_announces_default_route_between_allow_and_deny() {
        // a8o: filter order matters in babeld (first match wins) — the gateway
        // line must sit after the client-/24 allow and before the catch-all deny.
        let subnet: Ipv4Net = "10.42.1.0/24".parse().unwrap();
        let inputs = BabelConfigInputs::new(Some(subnet), &[]).gateway(true);
        let got = render_babeld_conf(&inputs);
        let allow = got.find("redistribute ip 10.42.1.0/24").unwrap();
        let gw = got
            .find("redistribute ip 0.0.0.0/0 le 0 metric 128")
            .unwrap();
        let deny = got.find("redistribute deny").unwrap();
        assert!(allow < gw && gw < deny, "bad filter order:\n{got}");
    }

    #[test]
    fn render_non_gateway_has_no_default_route_line() {
        let inputs = BabelConfigInputs::new(None, &[]);
        assert!(!render_babeld_conf(&inputs).contains("0.0.0.0/0"));
        assert!(
            !render_overlay_babeld_conf("mjolnir0", None, OverlayRtt::default(), false)
                .contains("0.0.0.0/0")
        );
    }

    #[test]
    fn render_overlay_gateway_announces_default_route() {
        let got = render_overlay_babeld_conf("mjolnir0", None, OverlayRtt::default(), true);
        let gw = got
            .find("redistribute ip 0.0.0.0/0 le 0 metric 128")
            .unwrap();
        let local_deny = got.find("redistribute local deny").unwrap();
        assert!(
            gw < local_deny,
            "gateway line must precede the local/catch-all denies:\n{got}"
        );
    }

    #[test]
    fn atomic_write_creates_file_when_missing() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("babeld.conf");
        let wrote = write_atomic_if_changed(&path, "hello").unwrap();
        assert!(wrote);
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "hello");
    }

    #[test]
    fn atomic_write_noop_when_unchanged() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("babeld.conf");
        std::fs::write(&path, "hello").unwrap();
        let wrote = write_atomic_if_changed(&path, "hello").unwrap();
        assert!(!wrote);
    }

    #[test]
    fn atomic_write_replaces_when_changed() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("babeld.conf");
        std::fs::write(&path, "hello").unwrap();
        let wrote = write_atomic_if_changed(&path, "world").unwrap();
        assert!(wrote);
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "world");
    }
}
