//! babeld configuration generation.
//!
//! mjolnir-mesh manages babeld's config file from CRDT state. The daemon
//! regenerates the file when its subnet claim or active-peer set changes,
//! writes atomically, and SIGHUPs babeld. See docs/network-coordination/
//! babel-routing.md §5.

use ipnet::Ipv4Net;
use std::io;
use std::path::Path;

/// Inputs to the config renderer. All fields are required.
#[derive(Debug, Clone)]
pub struct BabelConfigInputs<'a> {
    /// This router's claimed /24 (or larger). One per router. Optional only
    /// for the brief startup window before a claim has been published —
    /// during that window, no `redistribute ip` line is emitted.
    pub local_subnet: Option<Ipv4Net>,
    /// Per-peer TUN interface names currently up (from US-004's PeerInterface).
    pub peer_interfaces: &'a [&'a str],
    /// Default rxcost for tunneled neighbors. babeld defaults are 96 for
    /// non-multicast (tunnel) interfaces.
    pub tunnel_rxcost: u16,
}

impl<'a> BabelConfigInputs<'a> {
    /// Recommended defaults matching babel-routing.md §5.
    pub fn new(local_subnet: Option<Ipv4Net>, peer_interfaces: &'a [&'a str]) -> Self {
        Self {
            local_subnet,
            peer_interfaces,
            tunnel_rxcost: 96,
        }
    }
}

/// Render the full babeld.conf body. Pure — no I/O.
///
/// Output (golden, matches babel-routing.md §5):
/// ```text
/// # Generated by mjolnir-mesh — do not edit by hand
///
/// interface mj-peer-aabbccdd type tunnel
/// interface mj-peer-eeff0011 type tunnel
///
/// redistribute ip 10.42.1.0/24 ge 24 le 24 allow
/// redistribute local deny
/// redistribute proto static deny
/// redistribute proto kernel deny
///
/// in ip 10.255.0.0/16 deny
/// out ip 10.255.0.0/16 deny
///
/// default rxcost 96
/// ```
pub fn render_babeld_conf(inputs: &BabelConfigInputs<'_>) -> String {
    let mut out = String::new();
    out.push_str("# Generated by mjolnir-mesh — do not edit by hand\n\n");

    for iface in inputs.peer_interfaces {
        out.push_str(&format!("interface {} type tunnel\n", iface));
    }
    if !inputs.peer_interfaces.is_empty() {
        out.push('\n');
    }

    if let Some(subnet) = inputs.local_subnet {
        let prefix = subnet.prefix_len();
        out.push_str(&format!(
            "redistribute ip {} ge {} le {} allow\n",
            subnet, prefix, prefix
        ));
    }
    out.push_str("redistribute local deny\n");
    out.push_str("redistribute proto static deny\n");
    out.push_str("redistribute proto kernel deny\n\n");

    out.push_str("in ip 10.255.0.0/16 deny\n");
    out.push_str("out ip 10.255.0.0/16 deny\n\n");

    out.push_str(&format!("default rxcost {}\n", inputs.tunnel_rxcost));
    out
}

/// Write `contents` atomically to `path` — tmp file + rename in the same directory.
/// Returns `Ok(true)` if the file was written (content differed or didn't exist),
/// `Ok(false)` if the on-disk content already matched and no write was performed.
pub fn write_atomic_if_changed(path: &Path, contents: &str) -> io::Result<bool> {
    if let Ok(existing) = std::fs::read_to_string(path)
        && existing == contents
    {
        return Ok(false);
    }
    let parent = path.parent().ok_or_else(|| {
        io::Error::new(io::ErrorKind::InvalidInput, "config path has no parent dir")
    })?;
    // Random-ish suffix; collisions tolerable since we're single-process.
    let pid = std::process::id();
    let tmp = parent.join(format!(
        ".{}-{}.tmp",
        path.file_name().and_then(|n| n.to_str()).unwrap_or("babeld.conf"),
        pid
    ));
    std::fs::write(&tmp, contents)?;
    std::fs::rename(&tmp, path)?;
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_matches_golden_with_two_peers_and_subnet() {
        let subnet: Ipv4Net = "10.42.1.0/24".parse().unwrap();
        let peers = ["mj-peer-aabbccdd", "mj-peer-eeff0011"];
        let inputs = BabelConfigInputs::new(Some(subnet), &peers);
        let got = render_babeld_conf(&inputs);
        let expected = "\
# Generated by mjolnir-mesh — do not edit by hand

interface mj-peer-aabbccdd type tunnel
interface mj-peer-eeff0011 type tunnel

redistribute ip 10.42.1.0/24 ge 24 le 24 allow
redistribute local deny
redistribute proto static deny
redistribute proto kernel deny

in ip 10.255.0.0/16 deny
out ip 10.255.0.0/16 deny

default rxcost 96
";
        assert_eq!(got, expected);
    }

    #[test]
    fn render_omits_redistribute_when_no_local_subnet() {
        let peers = ["mj-peer-aabbccdd"];
        let inputs = BabelConfigInputs::new(None, &peers);
        let got = render_babeld_conf(&inputs);
        assert!(!got.contains("redistribute ip"), "should have no redistribute ip line");
        assert!(got.contains("redistribute local deny"));
        assert!(got.contains("redistribute proto static deny"));
        assert!(got.contains("redistribute proto kernel deny"));
    }

    #[test]
    fn render_with_no_peers_omits_interface_block() {
        let subnet: Ipv4Net = "10.42.1.0/24".parse().unwrap();
        let peers: &[&str] = &[];
        let inputs = BabelConfigInputs::new(Some(subnet), peers);
        let got = render_babeld_conf(&inputs);
        assert!(!got.contains("interface"), "should have no interface lines");
        // No double blank line where the block would have been — header blank + no extra
        let expected_start = "# Generated by mjolnir-mesh — do not edit by hand\n\nredistribute";
        assert!(
            got.starts_with(expected_start),
            "unexpected start:\n{got}"
        );
    }

    #[test]
    fn render_with_custom_rxcost() {
        let peers: &[&str] = &[];
        let mut inputs = BabelConfigInputs::new(None, peers);
        inputs.tunnel_rxcost = 200;
        let got = render_babeld_conf(&inputs);
        assert!(got.ends_with("default rxcost 200\n"));
    }

    #[test]
    fn atomic_write_creates_file_when_missing() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("babeld.conf");
        let wrote = write_atomic_if_changed(&path, "hello").unwrap();
        assert!(wrote);
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "hello");
    }

    #[test]
    fn atomic_write_noop_when_unchanged() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("babeld.conf");
        std::fs::write(&path, "hello").unwrap();
        let wrote = write_atomic_if_changed(&path, "hello").unwrap();
        assert!(!wrote);
    }

    #[test]
    fn atomic_write_replaces_when_changed() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("babeld.conf");
        std::fs::write(&path, "hello").unwrap();
        let wrote = write_atomic_if_changed(&path, "world").unwrap();
        assert!(wrote);
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "world");
    }
}
